config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
   resources :books, only: [:new, :create, :index, :show, :edit]
   resources :users, only: [:index, :show, :edit]
   get 'homes/about' => 'homes#about', as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  def get_image
    if image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
     books_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
    redirect_to books_path
  end

  def index
    @books = Book.all
    @book = Book.new
    
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

 private

 def book_params
  params.require(:book).permit(:title, :body)
 end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @books = Book.all
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @books = @user.books
  end
  
  def edit
    @user = User.find(params[:id])
  end

  private

  def user_params
   params.require(:user).permit(:name, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<% @books.each do |book| %>
<div class="container px-5 px-sm-0">
     <div class="row">
       
       <div class="col-md-3">
         <h2>User info</h2>
         <%= link_to book_path(book.id) do %>
         <p><%= image_tag book.user.get_profile_image(100,100) %></p>
         <% end %>
         <table class="table">
           <tbody>
             <tr></tr>
             <tr>
               <th>name<%= book.user.name %></th>
             </tr>
             <tr>
               <th>introduction<%= book.user.introduction %></th>
               <th></th>
             </tr>
           </tbody>
         </table>
          <% end %>
         <div class="row">
            <%= link_to @edit_user, class: "btn btn-outline-secondary btn-block" do %> 
            <i class="fa-solid fa-user-gear"></i>
            <% end %>
         </div>
         <h2 class="mt-3">New book</h2>
         <%= form_with model: @book do |f| %>
         <div class="form-group">
         <h4>Title</h4>
         <%= f.text_field :title %>
         </div>
         <div class="form-group">
         <h4>Opinion</h4>
         <%= f.text_area :body %>
         </div>
         <div class="form-group">
         <%= f.submit 'Crate Book'%>
         <% end %>
         </div>
         </div>
         <div class="col-md-8 offset-md-1">
            <h2>Books</h2>
            <table class="table table-hover table-inverse">
           
               <thead>
                <tr>
                  <tr></tr>
                  <th>Title</th>
                  <th>Opinion</th>
                  <th colspan="3"></th>
                </tr>
               </thead>
            <% @books.each do |book| %>
              </table>
            <% end %>
         </div>
       </div>
     </div>
   
</div>

app/views/books/show.html.erb
<div>
  <%= image_tag @book.get_image %>
  <p>Title  <%= @book.title %></p>
  <p>Opinion  <%= @book.body %></p>
  <p>name  <%= @book.user.name %></p>
  <p>introduction<%= @book.user.introduction %></p>
</div>

app/views/homes/about.html.erb
<main>
  <p id="notice"></p>
  <div class="container"></div>
    <div class="row">
      <div class="px-3 mx-auto">
        <h1>welcome to<i class="fa-solid fa-book"></i><strong>Bookers</strong> !!</h1>
      </div>
    </div>
   </div>
</main>

app/views/homes/top.html.erb
<main>
  <p id="notice"></p>
  <div class="container"></div>
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcom to<i class="fa-solid fa-book"></i><strong>Bookers</strong> !!</h1>
        <p>
          In<i class="fa-solid fa-book"></i><strong>Bookers</strong>,
        </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        
        <p>about various books!</p>
        <div class="btn-warapper col-10 mx-auto">
          <div class="row">
           <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3" %>
           <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block" %>
          </div>
        </div>
      </div>
    </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/f77519cc4e.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDoropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li>
                <%= link_to  root_path, class:"nav-link text-light" do  %>
                  <i class="fa-solid fa-house"></i>
                  Home
                <% end %>
              </li>
              <li>
                <%= link_to  users_path, class:"nav-link text-light" do %>
                  <i class="fa-solid fa-user"></i>
                  Users
                <% end %>
              </li>
              <li>
                <%= link_to books_path,  class:"nav-link text-light" do %>
                  <i class="fa-solid fa-book-open"></i>
                  Book
                <% end %>
              </li>
               <li>
                <%= link_to destroy_user_session_path, method: :delete , class:"nav-link text-light" do %>
                  <i class="fa-solid fa-arrow-right-from-bracket"></i>
                  Log out
                <% end %>
              </li>
              <% else %>
               <li>
                <%= link_to  root_path, class:"nav-link text-light" do  %>
                  <i class="fa-solid fa-house"></i>
                  Home
                <% end %>
              </li>
              <li>
                <%= link_to about_path, class:"nav-link text-light" do %>
                  <i class="fa-solid fa-link"></i>
                  about
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
                  <i class="fa-solid fa-user-plus"></i>
                  Sign up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path, class:"nav-link text-light" do %>
                  <i class="fa-solid fa-arrow-right-to-bracket"></i>
                  Log in
                <% end %>
              </li>
             <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
    <%= yield %>  
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>